# Generated by Django 4.2.5 on 2024-07-14 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendapipi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresaenvioclientes',
            options={'verbose_name': 'EmpresaEnvioClientes', 'verbose_name_plural': 'EmpresasEnvioClientes'},
        ),
        migrations.AlterModelOptions(
            name='proveedormercaderia',
            options={'ordering': ['-nombre'], 'verbose_name': 'ProveedorMercaderia', 'verbose_name_plural': 'ProveedoresrMercaderia'},
        ),
        migrations.AlterModelOptions(
            name='tiendamayorista',
            options={'ordering': ['apellido', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='tiendaminorista',
            options={'ordering': ['apellido', 'nombre']},
        ),
    ]
